version: '3'

services:
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"
  server:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
