version: '3'

services:
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DATABASE=${DATABASE}
    ports:
      - "5432:5432"
  server:
    restart: always
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    entrypoint: ["python", "app.py"]
