version: '3'

services:
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
  server:
    restart: always
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    entrypoint: ["python", "run.py"]
